server:
  port: 8084
spring:
  application:
    name: api-cuentas-operaciones
eureka:
  client:
    registry-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true